name:                matching
version:             0.1.0.0
github:              "kframework/llvm-backend"
license:             "UIUC"
author:              "Radu Ometita"
maintainer:          "radu.ometita@gmail.com"
copyright:           "2018 Runtime Verification, Inc."

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kframework/llvm-backend>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- text
- text-show
- yaml >= 0.10.3.0
- bytestring
- kore
- containers
- ilist
- tuple
- filepath
- directory
- free
- deriving-compat

default-extensions:
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - OverloadedStrings
  - TemplateHaskell
  - TupleSections
  - TypeSynonymInstances
  - UndecidableInstances
  - ScopedTypeVariables

executables:
  llvm-kompile-matching:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -rtsopts
      - -O2
    dependencies:
      - matching

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O3

tests:
  matching-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:        
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - matching
    - tasty
    - tasty-hunit
