name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: runtimeverification
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A llvm-backend -A llvm-backend-matching
    - run: nix-shell --run "echo OK"
    - run: nix-build test.nix
